const API_URL = 'http://localhost:8000/api'

const POLL_INTERVAL_MS = 2500
const HISTORY_POLL_INTERVAL_MS = 60000
const TRADE_BLOTTER_POLL_INTERVAL_MS = 3000
const DEFAULT_BANKROLL = 1000
const DEFAULT_KELLY = 0.25
const BET_LOCK_TTL_S = 5400
const MAX_FEED_ENTRIES = 120
const SOFA_LAG_OK_S = 30

const MARKET_KEYS = ['goles', 'corners', 'tarjetas']

const SIDE_OVER = 'OVER'
const SIDE_UNDER = 'UNDER'
const NO_BET = 'NO BET'
const PASAR = 'PASAR'

export {
  API_URL,
  POLL_INTERVAL_MS,
  HISTORY_POLL_INTERVAL_MS,
  TRADE_BLOTTER_POLL_INTERVAL_MS,
  DEFAULT_BANKROLL,
  DEFAULT_KELLY,
  BET_LOCK_TTL_S,
  MAX_FEED_ENTRIES,
  SOFA_LAG_OK_S,
  MARKET_KEYS,
  SIDE_OVER,
  SIDE_UNDER,
  NO_BET,
  PASAR,
}
